substitutions:
  _REGION: australia-southeast1
  _REPO: ingestion
  _IMAGE: macro-ingestor

# ✅ 新增這段，解掉 service_account 需要日誌策略的限制
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$COMMIT_SHA','.']
  - name: gcr.io/cloud-builders/docker
    args: ['push','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$COMMIT_SHA']

  - name: gcr.io/cloud-builders/gcloud
    args: ['run','jobs','update','ingest-fomc',
           '--region','$_REGION',
           '--image','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$COMMIT_SHA']
  - name: gcr.io/cloud-builders/gcloud
    args: ['run','jobs','update','ingest-bls',
           '--region','$_REGION',
           '--image','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$COMMIT_SHA']
  - name: gcr.io/cloud-builders/gcloud
    args: ['run','jobs','update','ingest-bea',
           '--region','$_REGION',
           '--image','$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$COMMIT_SHA']

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_IMAGE:$COMMIT_SHA'

